#
#
#
#         tttt                                                                      kkkkkkkk              ffffffffffffffff    1111111        888888888            444444444          66666666                    LLLLLLLLLLL                                                    iiii
#      ttt:::t                                                                      k::::::k             f::::::::::::::::f  1::::::1      88:::::::::88         4::::::::4         6::::::6                     L:::::::::L                                                   i::::i
#      t:::::t                                                                      k::::::k            f::::::::::::::::::f1:::::::1    88:::::::::::::88      4:::::::::4        6::::::6                      L:::::::::L                                                    iiii
#      t:::::t                                                                      k::::::k            f::::::fffffff:::::f111:::::1   8::::::88888::::::8    4::::44::::4       6::::::6                       LL:::::::LL
# ttttttt:::::ttttttt       ooooooooooo      mmmmmmm    mmmmmmm       eeeeeeeeeeee    k:::::k    kkkkkkk f:::::f       ffffff   1::::1   8:::::8     8:::::8   4::::4 4::::4      6::::::6                          L:::::L                  ooooooooooo      ggggggggg   gggggiiiiiiinnnn  nnnnnnnn
# t:::::::::::::::::t     oo:::::::::::oo  mm:::::::m  m:::::::mm   ee::::::::::::ee  k:::::k   k:::::k  f:::::f                1::::1   8:::::8     8:::::8  4::::4  4::::4     6::::::6                           L:::::L                oo:::::::::::oo   g:::::::::ggg::::gi:::::in:::nn::::::::nn
# t:::::::::::::::::t    o:::::::::::::::om::::::::::mm::::::::::m e::::::eeeee:::::eek:::::k  k:::::k  f:::::::ffffff          1::::1    8:::::88888:::::8  4::::4   4::::4    6::::::6                            L:::::L               o:::::::::::::::o g:::::::::::::::::g i::::in::::::::::::::nn
# tttttt:::::::tttttt    o:::::ooooo:::::om::::::::::::::::::::::me::::::e     e:::::ek:::::k k:::::k   f::::::::::::f          1::::l     8:::::::::::::8  4::::444444::::444 6::::::::66666     ---------------   L:::::L               o:::::ooooo:::::og::::::ggggg::::::gg i::::inn:::::::::::::::n
#      t:::::t          o::::o     o::::om:::::mmm::::::mmm:::::me:::::::eeeee::::::ek::::::k:::::k    f::::::::::::f          1::::l    8:::::88888:::::8 4::::::::::::::::46::::::::::::::66   -:::::::::::::-   L:::::L               o::::o     o::::og:::::g     g:::::g  i::::i  n:::::nnnn:::::n
#      t:::::t          o::::o     o::::om::::m   m::::m   m::::me:::::::::::::::::e k:::::::::::k     f:::::::ffffff          1::::l   8:::::8     8:::::84444444444:::::4446::::::66666:::::6  ---------------   L:::::L               o::::o     o::::og:::::g     g:::::g  i::::i  n::::n    n::::n
#      t:::::t          o::::o     o::::om::::m   m::::m   m::::me::::::eeeeeeeeeee  k:::::::::::k      f:::::f                1::::l   8:::::8     8:::::8          4::::4  6:::::6     6:::::6                   L:::::L               o::::o     o::::og:::::g     g:::::g  i::::i  n::::n    n::::n
#      t:::::t    tttttto::::o     o::::om::::m   m::::m   m::::me:::::::e           k::::::k:::::k     f:::::f                1::::l   8:::::8     8:::::8          4::::4  6:::::6     6:::::6                   L:::::L         LLLLLLo::::o     o::::og::::::g    g:::::g  i::::i  n::::n    n::::n
#      t::::::tttt:::::to:::::ooooo:::::om::::m   m::::m   m::::me::::::::e         k::::::k k:::::k   f:::::::f            111::::::1118::::::88888::::::8          4::::4  6::::::66666::::::6                 LL:::::::LLLLLLLLL:::::Lo:::::ooooo:::::og:::::::ggggg:::::g i::::::i n::::n    n::::n
#      tt::::::::::::::to:::::::::::::::om::::m   m::::m   m::::m e::::::::eeeeeeee k::::::k  k:::::k  f:::::::f            1::::::::::1 88:::::::::::::88         44::::::44 66:::::::::::::66                  L::::::::::::::::::::::Lo:::::::::::::::o g::::::::::::::::g i::::::i n::::n    n::::n
#        tt:::::::::::tt oo:::::::::::oo m::::m   m::::m   m::::m  ee:::::::::::::e k::::::k   k:::::k f:::::::f            1::::::::::1   88:::::::::88           4::::::::4   66:::::::::66                    L::::::::::::::::::::::L oo:::::::::::oo   gg::::::::::::::g i::::::i n::::n    n::::n
#          ttttttttttt     ooooooooooo   mmmmmm   mmmmmm   mmmmmm    eeeeeeeeeeeeee kkkkkkkk    kkkkkkkfffffffff            111111111111     888888888             4444444444     666666666                      LLLLLLLLLLLLLLLLLLLLLLLL   ooooooooooo       gggggggg::::::g iiiiiiii nnnnnn    nnnnnn
#                                                                                                                                                                                                                                                                     g:::::g
#                                                                                                                                                                                                                                                         gggggg      g:::::g
#                                                                                                                                                                                                                                                         g:::::gg   gg:::::g
#                                                                                                                                                                                                                                                          g::::::ggg:::::::g
#                                                                                                                                                                                                                                                           gg:::::::::::::g
#                                                                                                                                                                                                                                                             ggg::::::ggg
#                                                                                                                                                                                                                                                                gggggg

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

#  __  __       _          _____      _   _   _
# |  \/  |     (_)        / ____|    | | | | (_)
# | \  / | __ _ _ _ __   | (___   ___| |_| |_ _ _ __   __ _ ___
# | |\/| |/ _` | | '_ \   \___ \ / _ \ __| __| | '_ \ / _` / __|
# | |  | | (_| | | | | |  ____) |  __/ |_| |_| | | | | (_| \__ \
# |_|  |_|\__,_|_|_| |_| |_____/ \___|\__|\__|_|_| |_|\__, |___/
#                                                       __/ |
#                                                      |___/
Main-Settings:
  # Language defaults to English
  # Supported languages: Polish, English, Spanish, Chinese
  Language: English

  # Premium account registration !NOT IMPLEMENTED!
  Premium-Command: false

  # Password Requirements
  Password-Requirements:
    Minimum-length: 6  # Minimum password length (Set 0 to disbale)
    Password-simple: true  # Password Weakness Verification (blocked-passwords.yml File)

  Wrong-kick-password: false  # Kick a player after entering the wrong password

  Time-to-Login: 25  # Time to log in (Set 0 to disbale)
  Time-to-Register: 60  # Time to register (Set 0 to disbale)

  # Commands available before logging in
  Login-Command:
    - "login"
    - "log"
    - "l"
    - "register"
    - "reg"

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# Storage Configuration
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Storage:
  # Available types:
  # LOCAL: YML (default), JSON, H2, TOMEKDATA (legacy, not recommended)
  # REMOTE: MYSQL, MARIADB, POSTGRESQL
  Type: YML

  # HikariCP settings for database-based storage (H2/remote).
  Hikari:
    Maximum-Pool-Size: 10
    Minimum-Idle: 2
    Connection-Timeout: 30000
    Idle-Timeout: 600000
    Max-Lifetime: 1800000

  # H2 (local single file, no directory).
  H2:
    File-Name: "tomekf1846-login"
    Table-Name: "tomekf1846-login-users"
    Tables:
      Players: "tomekf1846-login-users"
      Security: "tomekf1846-login-users_security"
      Ip-History: "tomekf1846-login-users_ip_history"
    Username: "sa"
    Password: ""

  # Remote database settings (MySQL/MariaDB/PostgreSQL).
  Remote:
    Host: "localhost"
    Port: 3306
    Database: "minecraft"
    Username: "root"
    Password: ""
    Use-SSL: false
    Table-Name: "tomekf1846-login-users"
    Tables:
      Players: "tomekf1846-login-users"
      Security: "tomekf1846-login-users_security"
      Ip-History: "tomekf1846-login-users_ip_history"
    # Optional custom JDBC URL (overrides the settings above if provided)
    Jdbc-Url: ""
    # Optional extra JDBC parameters (e.g. "useUnicode=true&characterEncoding=utf8")
    Additional-Parameters: ""

#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# _    _      _     _                 _
#| |  | |    | |   | |               | |
#| |  | | ___| |__ | |__   ___   ___ | | __
#| |/\| |/ _ \ '_ \| '_ \ / _ \ / _ \| |/ /
#\  /\  /  __/ |_) | | | | (_) | (_) |   <
# \/  \/ \___|_.__/|_| |_|\___/ \___/|_|\_\
# SOON SOON SOON SOON SOON SOON SOON SOON SOON SOON
#-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
